# general
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'

# 5-core for beauty toys-and-games
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

show_progress: False
save_dataset: False
dataset_save_path: ~
# dataloader
save_dataloaders: True
dataloaders_save_path: 'dataloader/'
log_wandb: False
wandb_project: 'recbole'

# training settings
epochs: 300
train_batch_size: 1024 
learner: adam

learning_rate: 0.001
train_neg_sample_args:
  distribution: uniform
  sample_num: 1
eval_step: 1
stopping_step: 10
clip_grad_norm: ~
weight_decay: 0 #1e-6
loss_decimal_place: 4
require_pow: False

# evaluation settings
eval_args: 
  split: {'RS':[0.8,0.1,0.1]}
  group_by: user
  order: RO
  mode: full
repeatable: False
metrics: ["Recall","NDCG","Hit","Precision","MRR"]
topk: [20] #[50]
valid_metric: NDCG@20 #50
valid_metric_bigger: True
eval_batch_size: 4096
metric_decimal_place: 4